### ISSUE TITLE
Can't set file dynamically from html

### ISSUE THREAD

**Issue by ruslanef97** [latuminggi/pdf.js_readonly#1]
How to set file url dynamically from html file, cause currently loading file is on default configuration

**Comment by latuminggi** [comment]
hi @ruslanef97 
you can use iframe just like example here [/test/iframe_readonly.html](https://github.com/latuminggi/pdf.js_readonly/blob/master/test/iframe_readonly.html)
there's a query string `file` you can set to open pdf dynamically
i've added a demo to that iframe [here](https://latuminggi.github.io/pdf.js_readonly/test/iframe_readonly.html)
if you want to explore more you can refer to [PDF.js examples](https://mozilla.github.io/pdf.js/examples/)
