### ISSUE TITLE
decode base64

### ISSUE THREAD

**Issue by zulmarij** [latuminggi/pdf.js_readonly#2]
how to decode base64 in desktop view?
in mobile view using `const url = window.atob(params.url);` in file **viewer_mod.js**

**Comment by latuminggi** [comment]
you may refer to this [example](https://mozilla.github.io/pdf.js/examples/#:~:text=Hello%20World%20using%20base64%20encoded%C2%A0PDF) of _Hello World using base64 encoded PDF_
i myself never try it btw

**Comment by zulmarij** [comment]
ok.. thanks
