### ISSUE TITLE
Using framework codeigniter

### ISSUE THREAD

**Issue by adityoabdi** [latuminggi/pdf.js_readonly#3]
How we use pdf.js read only on codeigniter framework. And when query string for file , where i have to upload file pdf ? Assets or view . Pls info

**Comment by latuminggi** [comment]
hi, sorry for late response
you can upload this package into root folder of your project e.g. /var/www/html
if you see example of iframe in [demo](https://github.com/latuminggi/pdf.js_readonly#demo), you can make an iframe in views on your CI framework
you can put pdf files wherever you think secure and can NOT be accessed directly
mostly the directory of your pdf files should NOT be put on your root folder of your project
an example in php code to protect your pdf file is [here](https://github.com/latuminggi/pdf.js_readonly#how-to-protect-pdf-files-from-direct-access)

best regards
