### ISSUE TITLE
Using minified PDF.js files possible?

### ISSUE THREAD

**Issue by amrithyerramilli** [latuminggi/pdf.js_readonly#4]
Hi, I really like this code that you have shared - it has made it very easy to integrate a readonly version of pdf.js.

Would it be possible to use a minified version of pdf.js?
I was reading the [FAQ in the main repository](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#the-pdfjs-files-are-too-big-is-it-possible-to-obtain-minified-versions-of-the-js-files) - and it seems like it should be possible.

Could you guide me on the process to use the minified files (i.e which files do I replace with minified ones) ?

**Comment by latuminggi** [comment]
hi there,
i think you can modify unminified version first and then try to minify your custom js files, or
you can create an additional js file that modify how pdf.js works which i have no time for tweaking it :D
