### ISSUE TITLE
how i can implement this read only feature in a project , can you please make a video about this

### ISSUE THREAD

**Issue by ahmadgul12** [latuminggi/pdf.js_readonly#5]
i had a Laravel project which is using pdf.js, now how i can implement it in, a need a video about this

**Comment by latuminggi** [comment]
i use this on my laravel project too, but this can be separated from your own laravel project.
you can download this outside or inside public directory of your laravel project.
you can refer to issue #3 where it using codeigniter. you can use an [iframe](https://latuminggi.github.io/pdf.js_readonly/test/iframe_readonly.html) with source like
`http://localhost/pdf.js_readonly/generic/web/viewer_readonly.html?file=http://localhost/file.pdf`
i believe you can use this repo for your project as long as you follow [how to use](https://github.com/latuminggi/pdf.js_readonly#how-to-use).
